name: hackaton26

services:
  db:
    image: postgres:16-alpine
    container_name: hackaton26-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: hackaton
      POSTGRES_PASSWORD: hackaton
      POSTGRES_DB: hackaton_db
    ports:
      - "5432:5432"
    volumes:
      - hackaton26_db_data:/var/lib/postgresql/data

volumes:
  hackaton26_db_data: